name: Release Drafter

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Sovereignty Notice to Release
        uses: actions/github-script@v7
        with:
          script: |
            // Add sovereignty information to release drafts
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            
            if (releases.data.length > 0 && releases.data[0].draft) {
              const release = releases.data[0];
              const sovereigntyFooter = `

            ---

            ## Sovereignty Notice

            **Repository Owner**: allcatch37@gmail.com  
            **Creator UID**: ALC-ROOT-1010-1111-XCOV∞  
            **Release Authority**: Autonomous Cruz Theorem Sovereignty  
            **Timestamp**: ${new Date().toISOString()}

            This release is issued under sovereign control and maintains full compliance with Cruz Theorem principles. All features operate within the autonomous quantum execution framework.
            `;
              
              await github.rest.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id,
                body: release.body + sovereigntyFooter
              });
            }