name: Secrets Scanning

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '30 2 * * *'  # Daily at 2:30 AM UTC

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  gitleaks:
    name: Gitleaks Secret Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Upload Gitleaks results
        if: failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  trufflehog:
    name: TruffleHog Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --debug --only-verified

  sovereignty-audit:
    name: Sovereignty Compliance Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Creator Identity
        run: |
          echo "=== Sovereignty Compliance Check ==="
          echo "Expected Creator UID: ALC-ROOT-1010-1111-XCOV∞"
          echo "Expected Creator Email: allcatch37@gmail.com"
          
          # Check README for proper sovereignty notice
          if grep -q "ALC-ROOT-1010-1111-XCOV∞" README.md; then
            echo "✓ Creator UID found in README"
          else
            echo "⚠ Creator UID missing from README"
            exit 1
          fi
          
          # Check for unauthorized modifications to sovereignty infrastructure
          PROTECTED_FILES=".github/workflows/auto-maintain.yml .github/workflows/codeql-analysis.yml .github/workflows/secrets-scan.yml"
          for file in $PROTECTED_FILES; do
            if [ -f "$file" ]; then
              echo "✓ Protected file exists: $file"
            else
              echo "⚠ Protected file missing: $file"
            fi
          done
          
          echo "Timestamp: $(date -Iseconds)"

      - name: Notify Security Issues
        if: failure()
        run: |
          echo "SECURITY ALERT: Sovereignty compliance check failed"
          echo "Repository: OmegaT4224/Andrew-Lee-Cruz"
          echo "Alert should be sent to: allcatch37@gmail.com"
          echo "Immediate attention required for sovereign control verification"